# Generated by Django 3.2 on 2023-04-20 15:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('##FF9A53', 'breakfast'), ('#7FFF7E', 'lunch'), ('#A796FF', 'dinner')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
