# Generated by Django 3.2 on 2023-04-20 16:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favoriterecipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='shoprecipe',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FF9A53', 'breakfast'), ('#7FFF7E', 'lunch'), ('#A796FF', 'dinner')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
